# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-17 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('nota', models.CharField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('cpf', models.CharField(blank=True, default='', max_length=12, null=True, unique=True)),
                ('foto', models.URLField(blank=True, default='http://placehold.it/100x100', null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endere\xe7o')),
                ('numero', models.CharField(blank=True, max_length=5, null=True, verbose_name='N\xfamero')),
                ('complemento', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ponto de Refer\xeancia')),
                ('lat', models.CharField(blank=True, max_length=100, null=True)),
                ('lng', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco_completo', models.CharField(blank=True, max_length=300, null=True)),
                ('bairro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Bairro', verbose_name='Bairro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endere\xe7o')),
                ('numero', models.CharField(blank=True, max_length=5, null=True, verbose_name='N\xfamero')),
                ('complemento', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ponto de Refer\xeancia')),
                ('lat', models.CharField(blank=True, max_length=100, null=True)),
                ('lng', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.URLField(blank=True, default='http://placehold.it/100x100', null=True)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('is_online', models.BooleanField(default=False)),
                ('cnpj', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco_completo', models.CharField(blank=True, max_length=300, null=True)),
                ('bairro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Bairro', verbose_name='Bairro')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormaEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('forma', models.CharField(blank=True, choices=[('VOU BUSCAR', 'VOU BUSCAR'), ('MOTOBOY', 'MOTOBOY')], default='MOTOBOY', max_length=100, null=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('forma', models.CharField(blank=True, choices=[('CREDITO', 'CREDITO'), ('DEBITO', 'DEBITO'), ('DINHEIRO', 'DINHEIRO'), ('REFEICAO', 'REFEICAO')], default='DINHEIRO', max_length=100, null=True)),
                ('cartao', models.CharField(blank=True, choices=[('MASTERCARD', 'MASTERCARD'), ('VISA', 'VISA'), ('ELO', 'ELO'), ('VR', 'VR'), ('HIPERCARD', 'HIPERCARD'), ('SODEXO', 'SODEXO')], max_length=100, null=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FotoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('identificador', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('limitador', models.CharField(default='1', max_length=2)),
                ('tipo', models.CharField(default='radio', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('quantidade', models.CharField(blank=True, default='1', max_length=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('valor_total', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('u_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_from', to=settings.AUTH_USER_MODEL)),
                ('u_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('type_message', models.CharField(choices=[('NOVO_PEDIDO', 'NOVO_PEDIDO'), ('ADMIN_MESSAGE', 'ADMIN_MESSAGE')], max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Opcional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=10)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Grupo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpcionalChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ItemPedido')),
                ('opcional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Opcional')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('status_pedido', models.CharField(blank=True, choices=[('AGUARDANDO', 'AGUARDANDO'), ('PREPARANDO', 'PREPARANDO'), ('ENTREGANDO', 'ENTREGANDO'), ('ENTREGUE', 'ENTREGUE')], default='AGUARDANDO', max_length=100, null=True)),
                ('valor_total', models.CharField(max_length=10)),
                ('troco', models.CharField(max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cliente')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento')),
                ('forma_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FormaEntrega')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FormaPagamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(default='')),
                ('preco_base', models.CharField(max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pedido'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Produto'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Produto'),
        ),
        migrations.AddField(
            model_name='fotoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Produto'),
        ),
        migrations.AddField(
            model_name='classificacao',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pedido'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estabelecimento'),
        ),
    ]
