# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-17 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='esta_aprovada',
            field=models.BooleanField(default=False),
        ),
    ]
