# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-06 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.URLField(default='http://placehold.it/100x100'),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='foto',
            field=models.URLField(default='http://placehold.it/100x100'),
        ),
    ]
