# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-06 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180306_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.URLField(blank=True, default='http://placehold.it/100x100', null=True),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='foto',
            field=models.URLField(blank=True, default='http://placehold.it/100x100', null=True),
        ),
        migrations.AlterField(
            model_name='formaentrega',
            name='forma',
            field=models.CharField(blank=True, choices=[('VOU BUSCAR', 'VOU BUSCAR'), ('MOTOBOY', 'MOTOBOY')], default='MOTOBOY', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='forma',
            field=models.CharField(blank=True, choices=[('CREDITO', 'CREDITO'), ('DEBITO', 'DEBITO'), ('DINHEIRO', 'DINHEIRO'), ('REFEICAO', 'REFEICAO')], default='DINHEIRO', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fotoproduto',
            name='url',
            field=models.URLField(blank=True, default='http://placehold.it/200x200', null=True),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='quantidade',
            field=models.CharField(blank=True, default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status_pedido',
            field=models.CharField(blank=True, choices=[('AGUARDANDO', 'AGUARDANDO'), ('PREPARANDO', 'PREPARANDO'), ('ENTREGANDO', 'ENTREGANDO'), ('ENTREGUE', 'ENTREGUE')], default='AGUARDANDO', max_length=100, null=True),
        ),
    ]
