# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-06 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180306_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
    ]
