# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-13 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180306_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoproduto',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FormaEntrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FormaPagamento'),
        ),
    ]
