# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-20 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180320_1241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classificacao',
            new_name='Avaliacao',
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avalia\xe7\xe3o', 'verbose_name_plural': 'Avalia\xe7\xf5es'},
        ),
        migrations.AlterModelOptions(
            name='configuracaosistema',
            options={'verbose_name': 'Configura\xe7\xe3o do Sistema', 'verbose_name_plural': 'Configura\xe7\xe3o do Sistema'},
        ),
        migrations.AlterModelOptions(
            name='formaentrega',
            options={'verbose_name': 'Forma de Entrega', 'verbose_name_plural': 'Formas de Entrega'},
        ),
        migrations.AlterModelOptions(
            name='formapagamento',
            options={'verbose_name': 'Forma de Pagamento', 'verbose_name_plural': 'Formas de Pagamento'},
        ),
        migrations.AlterModelOptions(
            name='fotoproduto',
            options={'verbose_name': 'Foto de Produto', 'verbose_name_plural': 'Foto de Produtos'},
        ),
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item de Pedido', 'verbose_name_plural': 'Itens de Pedido'},
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AlterModelOptions(
            name='notificacao',
            options={'verbose_name': 'Notifica\xe7\xe3o', 'verbose_name_plural': 'Notifica\xe7\xf5es'},
        ),
        migrations.AlterModelOptions(
            name='opcional',
            options={'verbose_name': 'Opcional', 'verbose_name_plural': 'Opcionais'},
        ),
        migrations.AlterModelOptions(
            name='opcionalchoice',
            options={'verbose_name': 'Opcional Escolhido', 'verbose_name_plural': 'Opcionais Escolhidos'},
        ),
    ]
