# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-21 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180320_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pedido'),
        ),
    ]
