# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-16 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_produto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=12, null=True, unique=True),
        ),
    ]
