# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-21 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_notificacao_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status_pedido',
            field=models.CharField(blank=True, choices=[('AGUARDANDO', 'AGUARDANDO'), ('ACEITO', 'ACEITO'), ('REJEITADO', 'REJEITADO'), ('PREPARANDO', 'PREPARANDO'), ('ENTREGANDO', 'ENTREGANDO'), ('ENTREGUE', 'ENTREGUE')], default='AGUARDANDO', max_length=100, null=True),
        ),
    ]
